# Generated by tools/make-cask.sh from dist/JamCrate.dmg — do not edit the
# version or sha256 by hand; re-run the generator after each release.
cask "jamcrate" do
  version "0.9.1"
  sha256 "1ffed54e2b634081f31312a8eb2cf495be88854112096b2ec26aa638694db797"

  # No  stanza: Homebrew deprecated it and now verifies the URL domain
  # by default. Keeping it makes 254 kegs, 281,091 files, 9.8GB print a deprecation warning to every
  # user of the tap, and  does not flag it.
  url "https://github.com/vitas/jamcrate-beta/releases/download/v#{version}-beta/JamCrate.dmg"
  name "JamCrate"
  desc "Backing-track player with solo markers and loops"
  homepage "https://jamcrate.app/"

  livecheck do
    url "https://github.com/vitas/jamcrate-beta/releases"
    regex(/^v?(\d+(?:\.\d+)+)-beta$/i)
    strategy :github_releases
  end

  depends_on macos: :sonoma

  caveats <<~EOS
    This build is ad-hoc signed, so macOS blocks the first launch.
    Open it once via  System Settings → Privacy & Security → "Open Anyway",
    or right-click JamCrate.app and choose Open. Only needed once.
    Notarized builds will not need this.
  EOS

  app "JamCrate.app"
end
