# Generated by tools/make-cask.sh from dist/JamCrate.dmg — do not edit the
# version or sha256 by hand; re-run the generator after each release.
cask "jamcrate" do
  version "0.9.12"
  sha256 "17683b8d3d61d9950a4790dc02e985c1598b92b05dc4ace1667f3613b338df91"

  # No "verified" stanza: Homebrew deprecated it and now verifies the URL domain
  # by default. Keeping it makes brew info print a deprecation warning to every
  # user of the tap, and brew audit does not flag it.
  # (No backticks and no bare dollars anywhere in this heredoc: it is unquoted so
  #  that the version and sha256 above expand, which means shell substitution
  #  applies to comments too. Backticks here once ran brew info and inlined its
  #  output into this file.)
  url "https://github.com/vitas/jamcrate-beta/releases/download/v#{version}-beta/JamCrate.dmg"
  name "JamCrate"
  desc "Backing-track player with solo markers and loops"
  homepage "https://jamcrate.app/"

  livecheck do
    url "https://github.com/vitas/jamcrate-beta/releases"
    regex(/^v?(\d+(?:\.\d+)+)-beta$/i)
    strategy :github_releases
  end

  depends_on macos: :sonoma

  app "JamCrate.app"
end
